### ISSUE TITLE
update the ontology from the one used in production

### ISSUE THREAD

**Issue by loicjaouen** [LaDHUL/oeuvres-roud#48]
they two versions have diverged:
- the one used live in production
- the original one as source code in turtle file

in order to make further development on the ontology, we need to merge update the turtle file from the production

**Comment by elespdn** [comment]
How is that possible, that what is in master and in prod diverges? I
thought my local was different from master/prod.

Il mer 30 giu 2021, 08:44 Loïc Jaouen ***@***.***> ha scritto:

**Comment by loicjaouen** [comment]
Finally, it didn't really diverge.

What happens is that when we upgrade knora from a version to the next one, it does some changes to the triple store, so we should not expect the source turtle file to be identical to an export from the production triple store.

Then, comparing ontologies is tedious because even if it is human readable, it is not quite human friendly.

And when automated tools say they diverged, it is worth checking.

Things like this: https://github.com/LaDHUL/oeuvres-roud/commit/96ed126b2e6d6b3326ba38300611a2c6964cb1a6#r52897502

made me think that I might have started the [last update](43cbfa844179661de67fc07a8465c939ae85789d) from a local master branch that was not updated with the [previous change](83f82deadd692d2b8a09d963f6f8b1f8c1ed39a7).

But in facts the missing `guiOrder` are only on the `value` leg of the property which is meaningless and have probably been cut off by a knora upgrade.

I just had to make sure.

**Comment by elespdn** [comment]
@loicjaouen, I understand.

This means that if I have to update the onto (which I have to do it now, just a small update), I can create a new branch from master, right? Thanks

**Comment by loicjaouen** [comment]
if it is not too late, maybe just have a look at the only change in the onto:
https://github.com/LaDHUL/oeuvres-roud/pull/49/files#diff-67a97f7c30fcf60868ade8160005406981357f56d0e4e8f2cedf5d317cea0464R2413

then accept and merge the PR #49 before editing the ontology file again.

If you started editing it already, just go on, and I'll merge before releasing to prod.
